// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro', // Asegúrate que el ID coincida con tu archivo .md
      label: 'Introducción', // Mejorado el formato del título
      className: 'intro',
    },

    {
      type: 'category',
      label: 'Primeros pasos',
      items: ['primeros-pasos/acceder-inspector', 'primeros-pasos/interfaz-basica'],
      className: 'firts_steps',
    },

    {
      type: 'category',
      label: 'Guías esenciales',
      items: ['guias-esenciales/inspeccionar-html', 'guias-esenciales/modificar-css','guias-esenciales/depurar-diseños-responsivos'],
      className: 'essential_guides',
    },

    {
      type: 'category',
      label: 'Guías avanzadas',
      items: ['guias-avanzadas/depuración-JavaScript', 'guias-avanzadas/uso-consola-integrada','guias-avanzadas/analizar-rendimiento'],
      className: 'advanced_guides',
    },

    {
      type: 'category',
      label: 'Arquitectura del inspector',
      items: ['arquitectura-inspector/cómo-interactúa-navegador.', 'arquitectura-inspector/flujo-datos-tiempo-real'],
      className: 'architecture_inspector',
    },

    {
      type: 'category',
      label: 'Herramientas complementarias',
      items: ['herramientas-complementarias/network-análisis-solicitudes', 'herramientas-complementarias/performance-optimización-carga','herramientas-complementarias/application-gestión-almacenamiento'],
      className: 'complementary_tools',
    },

    {
      type: 'category',
      label: 'Depuración de red',
      items: ['depuración-red/monitorizar-solicitudes-http', 'depuración-red/analizar-tiempos-carga'],
      className: 'network_debugging',
    },

    {
      type: 'category',
      label: 'Optimización de rendimiento',
      items: ['optimizacion-rendimiento/identificar-cuellos-botella', 'optimizacion-rendimiento/uso-panel-lighthouse'],
      className: 'performance_optimization',
    },

    {
      type: 'category',
      label: 'Atajos y productividad',
      items: ['atajos-productividad/teclas-rápidas-esenciales', 'atajos-productividad/configuración-personalizada'],
      className: 'shortcuts_productivity',
    },

    {
      type: 'category',
      label: 'Solución de problemas comunes',
      items: ['solucion-problemas-comunes/errores-consola-frecuentes', 'solucion-problemas-comunes/elementos-no-detectados'],
      className: 'solution_common_problems',
    },

    {
      type: 'category',
      label: 'Actualizaciones y novedades',
      items: ['actualizaciones-novedades/historial-versiones', 'actualizaciones-novedades/mejoras-recientes'],
      className: 'updates_new_features',
    },
  ],

};

export default sidebars;
